//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tienda_Accesorios_Proyecto_SW.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compra()
        {
            this.DetalleCompras = new HashSet<DetalleCompra>();
        }
    
        public int IdCompra { get; set; }
        public System.DateTime FechaCompra { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<decimal> TotalCompra { get; set; }

        [JsonIgnore]
        public virtual Empleado Empleado { get; set; }
        [JsonIgnore]
        public virtual Proveedor Proveedor { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleCompra> DetalleCompras { get; set; }
    }
}
