//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tienda_Accesorios_Proyecto_SW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePedidoProveedor
    {
        public int Id { get; set; }
        public Nullable<int> PedidoId { get; set; }
        public Nullable<int> AccesorioId { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> PrecioCompra { get; set; }
    
        public virtual Accesorio Accesorio { get; set; }
        public virtual PedidoProveedor PedidoProveedor { get; set; }
    }
}
