//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tienda_Accesorios_Proyecto_SW.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Garantia
    {
        public int IdGarantia { get; set; }
        public Nullable<int> IdVenta { get; set; }
        public System.DateTime FechaInicioGarantia { get; set; }
        public System.DateTime FechaFinGarantia { get; set; }
        public string DescripcionGarantia { get; set; }

        [JsonIgnore]
        public virtual Venta Venta { get; set; }
    }
}
