//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tienda_Accesorios_Proyecto_SW.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class InventarioSede
    {
        public int IdInventario { get; set; }
        public Nullable<int> IdSede { get; set; }
        public Nullable<int> CodigoSKU { get; set; }
        public int CantidadDisponible { get; set; }

        [JsonIgnore]
        public virtual Producto Producto { get; set; }
        [JsonIgnore]
        public virtual Sede Sede { get; set; }
    }
}
