//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tienda_Accesorios_Proyecto_SW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoProveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PedidoProveedor()
        {
            this.DetallePedidoProveedors = new HashSet<DetallePedidoProveedor>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ProveedorId { get; set; }
        public Nullable<System.DateTime> FechaPedido { get; set; }
        public string Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePedidoProveedor> DetallePedidoProveedors { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
