//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tienda_Accesorios_Proyecto_SW.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class ProveedorProducto
    {
        public int IdProveedorProducto { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<int> CodigoSKU { get; set; }
        public decimal PrecioProveedor { get; set; }
        public Nullable<System.DateTime> FechaUltimaActualizacionPrecio { get; set; }

        [JsonIgnore]
        public virtual Producto Producto { get; set; }
        [JsonIgnore]
        public virtual Proveedor Proveedor { get; set; }
    }
}
